### ISSUE TITLE
Not working in Firefox 57

### ISSUE THREAD

**Issue by takirala** [noplanman/GitHub-Tweaks#19]
I tried with TamperMonkey and GreaseMonkey this doesn't seem to be working in the new Firefox quantum.

**Comment by noplanman** [comment]
Ok thanks for reporting, haven't tested with that yet!

**Comment by noplanman** [comment]
Right, this should be fixed with version 2.8, please give it a try @takirala 

It seems that Greasemonkey 4.0 is broken on FF 57, but it works perfectly fine with Tampermonkey 👍

(Violentmonkey doesn't work on FF 57, but does on Nightly 59, so there are some differences there too...)
